POST http://localhost:8080/register HTTP/1.1
content-type: application/json

{
  "username": "Hans",
  "email": "hans3@imglueck.de",
  "password": "123456"
}

###

GET http://localhost:8080/profile/Luben HTTP/1.1
